### ISSUE TITLE
Neptune 2D conflict

### ISSUE THREAD

**Issue by mlee12382** [andrewsuzuki/prusaslicer-elegoo-profiles#1]
First off thanks for making this profile, I have been trying to figure out how to set this up myself to make it easier to share with people instead of the longer process of modifying the ender 3 profile, I wish I had come across this earlier and I found it by accident trying to help someone find manuals for the older Neptune 1. Anyways now that I found it I noticed a couple of modifications that need to be made for the 2D to make it work better:
- You have single_extruder_multi_material_priming = 1 it should be set to 0 as this feature is not compatible with a single nozzle setup on the 2D. 
- Also it needs to unload the filament at the end of the print so end g-code should add:
- G1 X5 Y{print_bed_max[1]*0.8} F{travel_speed*60} ; present print **<<already in your end code**
- G1 E-80 F1600 ; unload filament **<<NEW**
- And to the start code insert a couple lines:
- G1 Z0.28 F240 ; move down to prime nozzle **<<already in your start code**
- G92 E0 ; reset extruder  **<< already in your start code**
- G1 E90 ; load filament **<<NEW**
- G92 E0 ; reset extruder **<<NEW**
- This will help to prepare for if the new print starts on the 2nd extruder instead of the first.
- Also I added thumbnail support by adding: thumbnails = 16x16,220x124 to the common settings, I added it above toolchange_gcode = since that's where it was on my ender 3 based setup not sure location really matters though.
You might also add commented out BLTouch gcode or add additional printers that are already setup for auto leveling my start code for BLTouch looks like this:

> G90 ; use absolute coordinates
> M83 ; extruder relative mode
> M140 S{first_layer_bed_temperature[0]} ; set final bed temp
> M104 S150 ; set temporary nozzle temp to prevent oozing during homing and auto bed leveling
> G4 S10 ; allow partial nozzle warmup
> G28 ; home all axis
> ;G29 ; auto bed levelling - remove ; at beginning of line to enable
> ;M420 S1 ; enable mesh - remove ; at beginning of line to enable
> G1 Z50 F240
> G1 X2 Y10 F3000
> M104 S{first_layer_temperature[0]} ; set final nozzle temp
> M190 S{first_layer_bed_temperature[0]} ; wait for bed temp to stabilize
> M109 S{first_layer_temperature[0]} ; wait for nozzle temp to stabilize
> G1 Z0.28 F240 ; move down to prime nozzle
> G92 E0 ; reset extruder
> G1 E90 ; load filament
> G92 E0 ; reset extruder
> G1 Y140 E10 F1500 ; prime the nozzle
> G1 X2.3 F5000 ; move over for second prime line
> G92 E0 ; reset extruder
> G1 Y10 E10 F1200 ; prime the nozzle
> G92 E0 ; reset extruder
Here's the modified .ini based on my comments but lacking BLTouch specific instances.
[ElegooINI.zip](https://github.com/andrewsuzuki/prusaslicer-elegoo-profiles/files/8457522/ElegooINI.zip)

**Comment by andrewsuzuki** [comment]
Thanks! Yep as noted in the readme/ini the section for the 2D is pretty much unmodified from the Creality CR-X, so thanks for shining some light on it. Can you open a pull request with the changes?

And since publishing this I created a new version based on the much cleaner Voron profiles profiles [here](https://github.com/slic3r/slic3r-profiles/blob/main/Voron.ini), but I haven't gotten around to pushing them to this repo yet. Mostly because I added some klipper-specific things.

**Comment by mlee12382** [comment]
Pull request submitted, If you decide to push them and need help testing let me know, I'm running Trey's newest Marlin 2.0.93 build on my 2D currently, haven't messed with Klipper yet, still playing around with the various features on Marlin, linear advance is my next project and then maybe setting up UBL instead of BiLinear.

**Comment by mlee12382** [comment]
Also I'm not 100% sure on the syntax for adding a mesh image for the bed so it shows the Neptune build plate instead of blank but if you're familiar with it and want to add it here's the file https://github.com/Toylerrr/ELEGOO_Neptune2_Cura/blob/main/meshes/elegoo_neptune_2.stl
I can do it manually in PrusaSlicer but then it points to a local file, I'm sure there's probably a way to make it generic so it works for everyone.

**Comment by andrewsuzuki** [comment]
There are already instructions for that in the readme :) PrusaSlicer looks in the vendor/Elegoo directory so it is generic, other than having to download it manually

**Comment by mlee12382** [comment]
Sweet I must have missed that haha.Thanks :)

**Comment by mlee12382** [comment]
Now I just have to figure out how to get my filaments that were based off the ender 3 profile to show up for the neptune lol. Any thoughts?

**Comment by mlee12382** [comment]
Nevermind figured it out, I used Notepad++ and had to replace vendor_creality with vendor_elegoo and now they all show up :)

**Comment by mlee12382** [comment]
Have you thought about actually submitting your profiles to Prusa so it can get added natively to the next release?  https://github.com/prusa3d/PrusaSlicer/wiki/Vendor-bundles-and-updating-process
